QueueForChildren/Controllers/KindergartenQueueController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using QueueForChildren.Data.Dtos.KindergartenQueue;
using QueueForChildren.Data.Entities;
using QueueForChildren.Data.Identity;
using QueueForChildren.Services.Kindergarten;
using QueueForChildren.Web.Interfaces;

namespace QueueForChildren.Controllers
{
    [Authorize]
    public class KindergartenQueueController : Controller
    {
        private readonly IRepository<KindergartenLanguage> _kindergartenLanguageRepository;

        private readonly IRepository<Kindergarten> _kindergartenRepository;

        private readonly IRepository<Address> _addressRepository;

        private readonly IRepository<Parent> _parentRepository;

        private readonly IRepository<Child> _childRepository;

        private readonly UserManager<User> _userManager;

        private readonly IKindergartenListGetService _kindergartenListGetService;

        private readonly IAppendToQueueService _appendToQueueService;

        private readonly IKindergartenQueueGetService _kindergartenQueueGetService;

        public KindergartenQueueController(IRepository<KindergartenLanguage> kindergartenLanguageRepository,
            IRepository<Kindergarten> kindergartenRepository, IRepository<Address> addressRepository,
            IRepository<Parent> parentRepository, IRepository<Child> childRepository, UserManager<User> userManager,
            IKindergartenListGetService kindergartenListGetService, IAppendToQueueService appendToQueueService, IKindergartenQueueGetService kindergartenQueueGetService)
        {
            _kindergartenLanguageRepository = kindergartenLanguageRepository;
            _kindergartenRepository = kindergartenRepository;
            _addressRepository = addressRepository;
            _parentRepository = parentRepository;
            _childRepository = childRepository;
            _userManager = userManager;
            _kindergartenListGetService = kindergartenListGetService;
            _appendToQueueService = appendToQueueService;
            _kindergartenQueueGetService = kindergartenQueueGetService;
        }
        
        [HttpGet]
        public IActionResult FindKindergarten()
        {
            var regions = _kindergartenRepository.GetAll()
                .Where(kindergarten => kindergarten.Address.MicroRegion != null)
                .Select(kindergarten => kindergarten.Address.MicroRegion)
                .Distinct()
                .ToArray();

            ViewBag.Regions = new SelectList(regions);
            ViewBag.Languages = new SelectList(_kindergartenLanguageRepository.GetAll()
                .Select(lang => lang.Name)
                .Distinct()
            );

            return PartialView("FindKindergarten");
        }

        public IActionResult KindergartenList()
        {
            var kindergartenList = _kindergartenListGetService.KindergartenList();
            return PartialView("KindergartenList", new KindergartenSelectDto()
            {
                Kindergartens = kindergartenList
            });
        }

        [HttpPost]
        public async Task<IActionResult> FindKindergarten(KindergartenFindDto dto)
        {
            var user = await _userManager.GetUserAsync(User);
            var list = _kindergartenListGetService.FindKindergarten(user, dto);

            var children = user.Parent.Children.Select(child => new
                {
                    child.Id,
                    Name = child.LastName + " " + child.Name[0] + ". " + child.MiddleName?[0] + ".",
                })
                .ToArray();

            ViewBag.Children = new SelectList(children, "Id", "Name");

            return PartialView("SelectKindergarten", new KindergartenSelectDto()
            {
                Kindergartens = list
            });
        }

        [HttpPost]
        public async Task<IActionResult> SendApplication([FromBody]SelectedDto dto)
        {
            var user = await _userManager.GetUserAsync(User);
            long.TryParse(dto.childId, out var _childId);
            long.TryParse(dto.kindergartenId, out var _kindergartenId);
            var child = _childRepository.GetById(_childId);
            var kindergarten = _kindergartenRepository.GetById(_kindergartenId);
            
            var msg = _appendToQueueService.AppendToQueue(user, child, kindergarten);

            return Json(new {success = true, data = msg});
        }
        
        public IActionResult SelectKindergartenQueue()
        {
            var schoolList = _kindergartenRepository.GetAll()
                .Select(kindergarten => new
                {
                    kindergarten.Id,
                    kindergarten.Name
                });
            
            ViewBag.KindergartenList = new SelectList(schoolList, "Id", "Name");
            return View();
        }

        public async Task<IActionResult> QueueList(long schoolId)
        {
            var user = await _userManager.GetUserAsync(User);
            ViewBag.ParentId = user.ParentId;

            var list = _kindergartenQueueGetService.GetQueueList(schoolId);
            return PartialView("_queueList", list);
        }
    }
}

QueueForChildren/Views/KindergartenQueue/FindKindergarten.cshtml
@using QueueForChildren.Data.Dtos.KindergartenQueue
@model KindergartenFindDto

<div class="text-center">
    <form method="post" id="findSchoolForm" asp-action="FindKindergarten" asp-controller="KindergartenQueue">
        <div class="form-group">
            <label asp-for="Language">Язык детского сада</label>
            <select class="form-control" asp-for="Language" asp-items="@ViewBag.Languages">
                <option disabled selected value="">Выберите язык</option>
            </select>
        </div>
        <div class="form-group">
            <label asp-for="Region">Район</label>
            <select class="form-control" asp-for="Region" asp-items="@ViewBag.Regions">
                <option disabled selected value="">Выберите район</option>
            </select>
        </div>
        <div class="form-group">
            <label asp-for="Radius">Радиус поиска</label>
            <input type="range" class="form-control" value="0" min="0" step="1" max="10" asp-for="Radius" oninput="radiusValue.innerText = this.value">
            <p id="radiusValue">0</p>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Найти</button>
    </form>
</div>

<script type="text/javascript">
    $('#findSchoolForm').submit(function (event) {
        event.preventDefault();
        let href = $(this).attr('action');
        fetchWithUpdateContent('#content', href, {
            method: 'POST',
            body: new FormData(this)
        });
    });
</script>

QueueForChildren/Views/KindergartenQueue/KindergartenList.cshtml
@using QueueForChildren.Data.Dtos.KindergartenQueue; 
@model KindergartenSelectDto    

<table class="table table-hover table-dark">
    <thead>
    <tr>            
        <th scope="col">Наименование</th>
        <th scope="col">Район</th>
        <th scope="col">Адрес</th>
        <th scope="col">Количество мест</th>
        <th scope="col">Язык обучения</th>
        <th scope="col">Рейтинг</th>
        <th scope="col">Номер телефона</th>
        <th hidden scope="col"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var row in Model.Kindergartens) {
        <tr class="kindergartenRow">                
            <td>@row.Name</td>
            <td>@row.MicroRegion</td>
            <td>@row.Address</td>
            <td>@row.FreePlaceCount</td>
            <td>@string.Join(", ", row.Languages.Select(lang => lang.Name))</td>
            <td>@row.Rating</td>
            <td>@row.Phone</td>
        </tr>
    }       
    </tbody>
</table>

QueueForChildren/Views/KindergartenQueue/SelectKindergarten.cshtml
@using QueueForChildren.Data.Dtos.KindergartenQueue; 
@model KindergartenSelectDto    

<table class="table table-hover table-dark">
    <thead>
    <tr>            
        <th scope="col">Наименование</th>
        <th scope="col">Район</th>
        <th scope="col">Адрес</th>
        <th scope="col">Количество мест</th>
        <th scope="col">Язык обучения</th>
        <th scope="col">Рейтинг</th>
        <th scope="col">Номер телефона</th>
        <th hidden scope="col"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var row in Model.Kindergartens) {
        <tr class="kindergartenRow">                
            <td>@row.Name</td>
            <td>@row.MicroRegion</td>
            <td>@row.Address</td>
            <td>@row.FreePlaceCount</td>
            <td>@string.Join(", ", row.Languages.Select(lang => lang.Name))</td>
            <td>@row.Rating</td>
            <td>@row.Phone</td>
            <td hidden class="kindergartenId">@row.Id</td>
        </tr>
    }       
    </tbody>
</table>

<div class="modal fade" id="childSelectModal" tabindex="-1" role="dialog" aria-labelledby="childSelectLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="childSelectLabel">Выберите ребенка</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label asp-for="ChildId" class="col-form-label">Ребенок:</label>
            <select class="form-control" asp-for="ChildId" asp-items="@ViewBag.Children">
              <option disabled selected value="">Выберите ребенка</option>
            </select>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
        <button id="sendApplication" type="button" class="btn btn-primary" disabled>Отправить заявление</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Сообщение</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="modal-body" class="modal-body">
        <div class="h-100 d-flex align-items-center justify-content-center">
          <div class="spinner-border" role="status">
            <span class="sr-only">Загрузка...</span>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

<script src="~/js/selectKindergarten.js" asp-append-version="true"></script>

QueueForChildren/Views/KindergartenQueue/SelectKindergartenQueue.cshtml
@{
    Layout = null;
}

<div class="text-center">
    <div class="form-group">
        <label for="Kindergarten">Детский сад</label>
        <select class="form-control" id="Kindergarten" asp-items="@ViewBag.KindergartenList">
            <option disabled selected value="">Выберите детский сад</option>
        </select>
    </div>
</div>

<div id="queueTable">
    
</div>

<script type="text/javascript">
    //$('select option:first').prop('selected', true);
    
    $('#Kindergarten').on('change', function (e){
            var valueSelected = this.value;            
            fetchWithUpdateContent('#queueTable', '/KindergartenQueue/QueueList?kindergartenId='+valueSelected);           
        });
               
    
</script>

QueueForChildren/Views/KindergartenQueue/_queueList.cshtml
@using QueueForChildren.Data.Dtos.Queue
@model IReadOnlyList<QueueBy>

<table class="table table-hover table-dark">
    <thead>
    <tr>            
        <th scope="col">Место</th>
        <th scope="col">Имя</th>
        <th scope="col">Льгота</th>
        <th scope="col">Дата подачи заявления</th>
        <th hidden scope="col"></th>
    </tr>
    </thead>
    <tbody>
    @{
        var place = 1;
        foreach (var row in Model)
        {
            <tr class="kindergartenRow">
                <td>@place</td>
                <td>@row.ChildName</td>
                <td>@row.IsBenefit</td>
                <td>@row.Date</td>
            </tr>
            place++;
        }
    }       
    </tbody>
</table>